### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by r00bal** [MrRafalGlowacki/goit-react-hw-02-feedback#1]
https://github.com/MrRafalGlowacki/goit-react-hw-02-feedback/blob/68f32ba034b56321fd87f978949a760aaf38a694/src/components/App.jsx#L4-L11

Ten komponent jest troche niepotrzebny, tylko dodatkowy wrapper... Samo `LeaveFeedback` można by już nazwać  jako 'App' i przekazać odrazu do wyświetlenie w index

**Comment by MrRafalGlowacki** [comment]
Zrobione
